### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by vinniedauer** [pattern-lab/edition-node-gulp#105]
I am using Pattern Lab Node- Gulp Edition `2.9.3` on `Mac`.

##### Expected Behavior
run patternlab:build
pattern lab instance is generated and launched in browser

##### Actual Behavior
```Loading engines from the core...


Loading engines from the edition or test directory...

  mustache: good to go

Done loading engines.


====[ Pattern Lab / Node - v2.9.3 ]====

[10:20:27] Using gulpfile ~/Documents/pattern-lab/gulpfile.js
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
```
Any insight would be appreciated.

**Comment by bmuenzenmeyer** [comment]
https://github.com/pattern-lab/edition-node-gulp/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20undefined

**Comment by vinniedauer** [comment]
Sorry for not checking closed issues! Thanks for redirecting me.
