### ISSUE TITLE
loadstarterkit fails with TypeError [ERR_INVALID_ARG_TYPE] when using Node 9

### ISSUE THREAD

**Issue by ThePeach** [pattern-lab/edition-node-gulp#112]
I am using Pattern Lab Node- Gulp Edition `v1.4.0` on `Linux`.

##### Expected Behavior

When loading a starterkit I should have no problems and this should be the output:

```
$ npm run gulp -- patternlab:loadstarterkit --kit=starterkit-mustache-demo

> edition-node-gulp@1.4.0 gulp /home/peach/public_html/edition-node-gulp
> gulp "patternlab:loadstarterkit" "--kit=starterkit-mustache-demo"

Loading engines from the core...


Loading engines from the edition or test directory...

  mustache: good to go

Done loading engines.


====[ Pattern Lab / Node - v2.12.0 ]====

[14:39:52] Using gulpfile ~/public_html/edition-node-gulp/gulpfile.js
[14:39:52] Starting 'patternlab:loadstarterkit'...
Attempting to load starterkit from /home/peach/public_html/edition-node-gulp/node_modules/starterkit-mustache-demo/dist
Overwriting contents of ./source/ during starterkit load.
starterkit starterkit-mustache-demo loaded successfully.
[14:39:52] Finished 'patternlab:loadstarterkit' after 32 ms
``` 

##### Actual Behavior

When using Node 9 I get the following:

```
$ npm run gulp patternlab:loadstarterkit --kit=starterkit-mustache-demo

> edition-node-gulp@1.4.0 gulp /home/peach/public_html/edition-node-gulp
> gulp --  "patternlab:loadstarterkit"

Loading engines from the core...


Loading engines from the edition or test directory...

  mustache: good to go

Done loading engines.


====[ Pattern Lab / Node - v2.12.0 ]====

[14:27:16] Using gulpfile ~/public_html/edition-node-gulp/gulpfile.js
[14:27:16] Starting 'patternlab:loadstarterkit'...
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.join (path.js:1249:7)
    at loadStarterKit (/home/peach/public_html/edition-node-gulp/node_modules/patternlab-node/core/lib/starterkit_manager.js:19:14)
    at Object.load_starterkit (/home/peach/public_html/edition-node-gulp/node_modules/patternlab-node/core/lib/starterkit_manager.js:103:7)
    at loadStarterKit (/home/peach/public_html/edition-node-gulp/node_modules/patternlab-node/core/lib/patternlab.js:286:24)
    at Object.loadstarterkit (/home/peach/public_html/edition-node-gulp/node_modules/patternlab-node/core/lib/patternlab.js:646:7)
    at /home/peach/public_html/edition-node-gulp/gulpfile.js:147:14
    at taskWrapper (/home/peach/public_html/edition-node-gulp/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
[14:27:16] Finished 'patternlab:loadstarterkit' after 14 ms
```

##### Steps to Reproduce

Install Node 9

    $ npm install
    $ npm install starterkit-mustache-demo
    $ npm run gulp -- patternlab:loadstarterkit --kit=starterkit-mustache-demo

**Comment by webegguk** [comment]
+1 exactly the same issue unfortunately. Obviously you are able to manually install these but it would be much better if it worked as per documentation.. I'm using patternlab-node edition gulp from here https://github.com/pattern-lab/edition-node-gulp/releases/tag/v1.3.4 as per download page.
