### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by digitalclover** [pattern-lab/edition-node-gulp#61]
I am using Pattern Lab Node v6.2.2 on Windows & Mac, using the `gulp` configuration.
##### Expected Behavior

After installing npm packages, gulp should be able to perform its defined tasks in /gulpfile.js
##### Actual Behavior

All gulp tasks results in thrown error.  
Full output:

```
Loading engines...
...scanning for engines in the core...
- mustache engine: good to go
...scanning for engines in the edition or test directory...
...done loading engines.

[10:25:17] Using gulpfile ~/[...]/edition-node-gulp/gulpfile.js
/[...]/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /opt/local/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
```
##### Steps to Reproduce

Issue is duplicated on both Windows 10 & OSX
1. Clone git repository
2. Run 'npm install' (gulp already installed globally)
3. Run any gulp command

**Comment by bmuenzenmeyer** [comment]
Hi @digitalclover thanks for the issue report.

My current guess is this is an environment thing. I can run the repo clean on Node `5.5.0` but don't have ncu on my work rig to try it at Node 6.X yet.

Pattern Lab Core is covered by travis, but the editions are not yet.
Sit tight!

**Comment by bmuenzenmeyer** [comment]
could you also provide the results of `gulp -v` ?

**Comment by levimcg** [comment]
Hey, @bmuenzenmeyer I'm getting the same error shown above. Here's my results from `gulp -v`

```
CLI version 3.9.1
Local version 4.0.0-alpha.2
```

Thanks, really looking forward to checking out Patternlab!

**Comment by bmuenzenmeyer** [comment]
Your gulp CLI is wrong.

https://github.com/pattern-lab/edition-node-gulp/wiki/Updating-to-Gulp-4

**Comment by levimcg** [comment]
Yep, just realized that. Sorry! Everything is working fine now. Thanks for the reply.

**Comment by bmuenzenmeyer** [comment]
Yay! Finding the ways in which [this error manifests](https://github.com/pattern-lab/edition-node-gulp/issues/51) is important for future users. Thanks again for taking the time to use Pattern Lab!

**Comment by digitalclover** [comment]
Confirmed that I had Gulp 3.x running on both machines.  Upgrading to 4.x fixed this issue.  Thank you.

**Comment by bmuenzenmeyer** [comment]
lol i didn't realize there was two of you, but nice that it resolved both of your issues.

**Comment by skyelves** [comment]
I have tried the method you mentioned, but my CLI version is still 3.9.1.
Is that something wrong with my node version(6.9.5)?

**Comment by encrypted-yknev** [comment]
After upgrading my gulp-cli version, gulp -v still shows the same
`[00:13:30] CLI version 3.9.1
 [00:13:30] Local version 4.0.0`

Any suggestions what can be the issue?

node -v : `v7.10.1`
npm -v : `v4.2.0`

**Comment by sabbiseaan** [comment]
npm i -g gulp-cli 
is fix my issue

**Comment by bmuenzenmeyer** [comment]
What folks most likely want is `npm install --save-dev gulp@next`

pretty quick troubleshooting output below

```
brian@DESKTOP-TCM0GPM MINGW32 /d/src/pl-migrate-example (master)
$ gulp -v
[15:18:50] CLI version 2.0.1

brian@DESKTOP-TCM0GPM MINGW32 /d/src/pl-migrate-example (master)
$ gulp patternlab:serve
[15:18:55] Local gulp not found in D:\src\pl-migrate-example
[15:18:55] Try running: npm install gulp

brian@DESKTOP-TCM0GPM MINGW32 /d/src/pl-migrate-example (master)
$ npm install gulp
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, follo                                                                  wing the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for comp                                                                  atibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher                                                                   to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher                                                                   to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compa                                                                  tibility with current and future versions of Node.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fse                                                                  vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                                  1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}                                                                  )

+ gulp@3.9.1
added 243 packages in 26.565s

brian@DESKTOP-TCM0GPM MINGW32 /d/src/pl-migrate-example (master)
$ gulp patternlab:serve
Loading engines from the core...


Loading engines from the edition or test directory...

  mustache: good to go

Done loading engines.


====[ Pattern Lab / Node - v2.12.0 ]====

D:\src\pl-migrate-example\gulpfile.js:87
  gulp.parallel(
       ^

TypeError: gulp.parallel is not a function
    at Object.<anonymous> (D:\src\pl-migrate-example\gulpfile.js:87:8)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at execute (C:\Users\brian\AppData\Roaming\nvm\v8.9.4\node_modules\gulp-cli\                                                                  lib\versioned\^3.7.0\index.js:28:18)
    at Liftoff.handleArguments (C:\Users\brian\AppData\Roaming\nvm\v8.9.4\node_m                                                                  odules\gulp-cli\index.js:175:63)

brian@DESKTOP-TCM0GPM MINGW32 /d/src/pl-migrate-example (master)
$ ^C

brian@DESKTOP-TCM0GPM MINGW32 /d/src/pl-migrate-example (master)
$ gulp -v
[15:20:05] CLI version 2.0.1
[15:20:05] Local version 3.9.1

brian@DESKTOP-TCM0GPM MINGW32 /d/src/pl-migrate-example (master)
$ npm install gulp@next
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fse                                                                  vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                                  1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}                                                                  )

+ gulp@4.0.0
added 141 packages, removed 64 packages and updated 12 packages in 24.256s

brian@DESKTOP-TCM0GPM MINGW32 /d/src/pl-migrate-example (master)
$ gulp -v
[15:21:40] CLI version 2.0.1
[15:21:40] Local version 4.0.0

brian@DESKTOP-TCM0GPM MINGW32 /d/src/pl-migrate-example (master)
$ gulp patternlab:serve
Loading engines from the core...


Loading engines from the edition or test directory...

  mustache: good to go

Done loading engines.


====[ Pattern Lab / Node - v2.12.0 ]====

... etc

```

**Comment by dhirendrapratapsingh** [comment]
I tried everythinbg in sequence from above nothing worked

After upgrading my gulp-cli version, gulp -v still shows the same
still its showing
gulp -v
[16:40:55] CLI version 3.9.1
[16:40:55] Local version 4.0.0

npm install --save-dev gulp@next did not work showed this
![Screenshot from 2019-04-19 16-42-05](https://user-images.githubusercontent.com/32532380/56421880-41e1b800-62c2-11e9-9218-6f9c7aacad3c.png)

**Comment by submagr** [comment]
Even I tried everything mentioned above:
```
npm uninstall gulp
npm uninstall -g gulp-cli
npm install -g gulp-cli
npm install gulp
```
But the error still persisted.

**The following things worked for me:**
Manually delete gulp and gulp-cli, packages and binaries from everywhere:
1. ```~/.nvm/versions/node/v12.1.0/bin```
2. ```~/.nvm/versions/node/v12.1.0/lib/node_modules ```
3. ```/usr/local/bin```
4. ```/usr/local/lib/node_modules/```

I think the difference between package install locations of nvm and default node was messing up for me.

**Comment by nolawnchairs** [comment]
Same issue. 
```
CLI version 3.9.1
Local version 4.0.2
```
Still get this error
uninstalled gulp locally
uninstalled gulp globally
uninstalled gulp-cli globally
rm -rf'ed node_modules
uninstalled node, reinstalled node
reinstalled operating system, changed internet providers, moved house, got a sex change
STILL not working.
