### ISSUE TITLE
patternlab:build error

### ISSUE THREAD

**Issue by joxa83** [pattern-lab/edition-node-gulp#62]
I am using Pattern Lab Node `v1.2.3` on `Windows7`, using the `gulp` configuration.

after running gulp patternlab:build the following error happens

> C:\projects_node\edition-node-gulp-1.2.3>gulp patternlab:build
> 
> Loading engines...
> ...scanning for engines in the core...
> ...scanning for engines in the edition or test directory...
> - mustache engine: good to go
>   ...done loading engines.
> 
> [18:00:58] Using gulpfile C:\projects_node\edition-node-gulp-1.2.3\gulpfile.js
> [18:00:58] Starting 'patternlab:build'...
> [18:00:58] Starting 'pl-assets'...
> [18:00:58] Starting 'pl-copy:js'...
> [18:00:58] Starting 'pl-copy:img'...
> [18:00:58] Starting 'pl-copy:favicon'...
> [18:00:58] Starting 'pl-copy:font'...
> [18:00:58] Starting 'pl-copy:css'...
> [18:00:58] Starting 'pl-copy:styleguide'...
> [18:00:58] Starting 'pl-copy:styleguide-css'...
> [18:00:58] Finished 'pl-copy:js' after 31 ms
> [18:00:59] Finished 'pl-copy:favicon' after 71 ms
> [18:00:59] Finished 'pl-copy:css' after 77 ms
> [18:00:59] Finished 'pl-copy:styleguide-css' after 89 ms
> [18:00:59] Finished 'pl-copy:font' after 94 ms
> [18:00:59] Finished 'pl-copy:img' after 128 ms
> [18:00:59] Finished 'pl-copy:styleguide' after 133 ms
> [18:00:59] Starting '<anonymous>'...
> [18:00:59] Finished '<anonymous>' after 1.22 ms
> [18:00:59] Finished 'pl-assets' after 142 ms
> [18:00:59] Starting 'build'...
> [18:00:59] 'build' errored after 377 ms
> [18:00:59] TypeError: Path must be a string. Received undefined
>     at assertPath (path.js:7:11)
>     at Object.extname (path.js:889:5)
>     at C:\projects_node\edition-node-gulp-1.2.3\node_modules\patternlab-node\cor
> e\lib\media_hunter.js:13:16
>     at diveSync (C:\projects_node\edition-node-gulp-1.2.3\node_modules\diveSync\
> diveSync.js:62:5)
>     at findMediaQueries (C:\projects_node\edition-node-gulp-1.2.3\node_modules\p
> atternlab-node\core\lib\media_hunter.js:12:5)
>     at Object.find_media_queries (C:\projects_node\edition-node-gulp-1.2.3\node_
> modules\patternlab-node\core\lib\media_hunter.js:34:7)
>     at buildFrontEnd (C:\projects_node\edition-node-gulp-1.2.3\node_modules\patt
> ernlab-node\core\lib\ui_builder.js:420:16)
>     at Object.build (C:\projects_node\edition-node-gulp-1.2.3\node_modules\patte
> rnlab-node\core\lib\patternlab.js:366:7)
>     at build (C:\projects_node\edition-node-gulp-1.2.3\gulpfile.js:79:14)
>     at bound (domain.js:280:14)
> [18:00:59] 'patternlab:build' errored after 530 ms

**Comment by bmuenzenmeyer** [comment]
The code the stack trace is referring to has been removed in core.

Run `npm update` from your command line and try again please.

**Comment by joxa83** [comment]
after running `npm update` other error happened

[npm_debug.txt](https://github.com/pattern-lab/edition-node-gulp/files/370581/npm_debug.txt)

**Comment by bmuenzenmeyer** [comment]
Do you have [git](https://git-scm.com/downloads) installed?

**Comment by joxa83** [comment]
Yes I do have. I've also run `npm update` from GitBash, the same error happened.

**Comment by bmuenzenmeyer** [comment]
Hmm. I have confirmed I can run fine on:
- Windows 10
- Node 6.2.2
  Gulp CLI 1.2.1
  Gulp Local 4.0.0-alpha.2

Please let me know what the result of `gulp -v` is.

---

It seems to be erroring while trying to clone to appdata\roaming stating you don't have correct access rights. As far as I know you should be able to clone just fine...

```
C:\\Users\\40204187\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-https-github-com-gulpjs-gulp-git-4-0-4b46db44
```

Did you see what is at this location?

Some other things to try...
- `npm cache clear`
- review what is installed globally
- open command prompt as administrator

**Comment by joxa83** [comment]
glup 
CLI 1.2.2
Local 4.0.0-alpha.2

node
v6.3.0

I tried 
run as Administrator
npm cache clear

still the same.

The above-mentioned directory is empty.

no idea

**Comment by dillonlara115** [comment]
I got this working on 2 different computers by ensuring node, npm and gulp were all up to date.

**Comment by bmuenzenmeyer** [comment]
closing this due to inactivity
